[package]
name = "peerjs_app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
webbrowser = "1.0"
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
